services:
 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: py-container3
    restart: on-failure
    networks:
      - jenkins
    #command: python3 main.py

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins_home:
  jenkins_ssl:
  jenkins-docker-certs:
