services:
 
  app:
    build:
      context: ../docker-compose.yml
      dockerfile: Dockerfile
    container_name: py-container
    restart: on-failure
    depends_on:
      - docker
    networks:
      - jenkins
    #command: python3 main.py

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins_home:
  jenkins_ssl:
  jenkins-docker-certs:
